{% set name = "mpl-scatter-density" %}
{% set version = "0.4" %}
{% set sha256 = "0ddffbfa0e54fb9ea0032595ef868870a77ef2e87fb1fce935527026fb01099d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy >=1.11
    - matplotlib >=1.5
    - fast-histogram >=0.3
  run:
    - python
    - numpy >=1.11
    - matplotlib >=1.5
    - fast-histogram >=0.3

test:
  imports:
    - mpl_scatter_density

about:
  home: http://github.com/astrofrog/mpl-scatter-density
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib helpers to make density scatter plots
  description: Matplotlib helpers to make density scatter plots
  doc_url: http://github.com/astrofrog/mpl-scatter-density
  dev_url: http://github.com/astrofrog/mpl-scatter-density

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
