travis:
  secure:
    BINSTAR_TOKEN: OCesnBLxVFBKTDZFLxO55enfEOkwJvtSVGh6EDdbII8emVS1elfqeR0RUdAWL5kUUbUKCwYetc1dBs3HvtsztH3hhtkclIpc77x4AO/wk4rfJx/ukxjP9Qn8QK5yNjuAPJ9Qc6qQ35wypxx+rigzLO2gGuYCQ+X9Rhe2GTrZ2ajXyzYXh37O9UHXu2WrpfmqnlW3UCgGHI2tktr4VwHMm9QKZLnRR4KeQscYwF/z96S2riUJRBonztqoX9gwAZp1oOO+keOjw4WQFfFUuzdlqH/b5iAKpFfTxLft3tqmFXdWKYSINg0AVGRhmfH6zJJign1lOoaqqa9BTMC1jGWEvcqJAMGeGFiqQ5hlnHvs4fQ3UgUW29p0oEDQj55Bt2rz03pCIvd5b5DR487WUVKbok9RTUCs52eze109KDbbyMm2tPJEq4hFgzq/fNcPKbQIVmshve3aK2UsEwYBf9Q1Zdjf+5NT9IIdBLKtnnrDO4KU8unI6Q6FNBcJ7qC1FOJ3891CxQgY5EyNgu8Jt+zCf1K1dKbyHvs4BhljzC2UxncL1Nahzz+sIN0373kx9h7wXhdtpeBbbmnaQFVZ2LboaDgYn3hPZCl5x01eIankIbe2pER6c2FTG1iq5VL+3aB4Y0WHEH1kFLgnrm78Uefm+EYI7wONWl/ntesxQmIVNiY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
