travis:
  secure:
    BINSTAR_TOKEN: gKpJgagu33nsfv53utb0bspD60CV8ap7QYWbpbtOQ5agK2jW9OsoKUE2NHnKKCzKpuMK/XmmyZXYoU3K70eOvVaYbXgnwmFQvRjM08zR9NO/fucZvK+2FuZkUiuC5rrSsz5lTSAkGgh+7oiGMkh9rwPJ0WQZ1TqQAWcIrXI0yihMANewutRqNQM+B4pSRDSLhMKyO1HgdqeOaMpYgHRpHKdmr5Kk909zk1f9DsQ2mJjL7K1PrHVpm5vCnvEeuGPZHRWOzCuaCo/Jr8JHqFm2Av1XhAIgtGqy1A5XSw6dXb6eW30WLxcgk55l7MmgRlCH/z8KBRqBoCqm1h+mLShfUlyxfsGGmZlUiz/lUUlkHX/qIFigoNPHu4kacsOujJNzid/O5DtmMrAjSOTUecDbM+oK7N9il6BaEHafxIslUDtelEP3rl2p/idLvas/rdM56HGELMidzJmcXEjLnzs2/nwSFcHLSch5B2jdddoOk2LUjtZ5Nt2Vz9VWwdN/KJYQfZtbwtcYjzmhEvere+BChY4M4s/rcF5SDVBfYihInV20/jgEnGT5oMBfc426D396COluIrh+FVoCT2QviCXshfJNXzEgzu325qENP73PFs7X6VqIjkzdiQdlUTZ0PioLQD0Ko+37dWzwt1ghHmXEvlIZqblcwTergXwS+JeKsEk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
