travis:
  secure:
    BINSTAR_TOKEN: rvHEG3ggExUBESjX94Y/RVGFAPeSHNW96Y9wpF09W1CsCjDAPtGkOhxUembqURGHVn8U/PKE+7457vRdLOIiAqxzO7AKnCIv+659LGTvwMyrADnBKN3fd7vNvQB/8EViccFVzq7VH7pRwi2BmrTBpAhv/GeJ0+2+lDxM+YlZoWmYVirTBAfIAVxBZdxCrareMo04V69FE2rvevs3CCrpNtAQdh6PvyA/L0IMFDh6+okL7kN+1vgq5ngMv1dV6+WZ2VtsNT2F59IZtDTg3z6b3TDuG/hfPgcfEPkrWQXDCK4QbYnQBtOj3G8YT30frhFopqLWal2DMPmG7tZ/h2Pr+23ZXgjj/2i5OTsDlLe70RsbX2iNLlddybeL5AhJwcqxr6mmV1phAyNG+EGb9+eF9i3WMaXVxY39DpO2fYChHNMmkstnBoDDoPgsYhZy8SKYEYIbnuk0dHe2R7grYqEgsxpGlqLOxbUUu1YSF0zcy2MXtj/3tm9/XoKW3zox285IdvVYfBF/i3FGgiRcwSLHHON4MhWXIpVjKouaHYX4iIlC/tVbkxH2/2cNC1qNf954sKKC7hE94rIZdRlcFzD5j/lq2plErLEI1LTTqLYUUZhaa/roJ+a1iMPV1JN4xV4z5czeIFbGqDyneuR8EcSD2UQjknzusuvq6H0WoCSkDl4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
